general =
{
    name = "Ubuntu Amp";
    interpolation = "soxr";
};

alsa =
{
    output_device = "airplay_softvol";
    # No mixer_control_name means it handles volume internally
    ignore_volume_control = "yes";
};
